<?php
	$b_table="wp_commentmeta,wp_comments,wp_links,wp_options,wp_postmeta,wp_posts,wp_ratings,wp_term_relationships,wp_term_taxonomy,wp_terms,wp_usermeta,wp_users,wp_wp_rp_tags";
	$tb[wp_commentmeta]=1;
$tb[wp_comments]=1;
$tb[wp_links]=1;
$tb[wp_options]=1;
$tb[wp_postmeta]=1;
$tb[wp_posts]=5;
$tb[wp_ratings]=1;
$tb[wp_term_relationships]=1;
$tb[wp_term_taxonomy]=1;
$tb[wp_terms]=1;
$tb[wp_usermeta]=1;
$tb[wp_users]=1;
$tb[wp_wp_rp_tags]=1;

	$b_baktype=0;
	$b_filesize=300;
	$b_bakline=500;
	$b_autoauf=1;
	$b_dbname="df062bdee4c5349b3b860fe0dd5000ab6";
	$b_stru=1;
	$b_strufour=0;
	$b_dbchar="auto";
	$b_beover=0;
	$b_insertf="replace";
	$b_autofield=",,";
	$b_bakdatatype=0;
	?>